os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852
  # - . ~/.swiftenv/init
  - ~/.swiftenv/bin/swiftenv install DEVELOPMENT-SNAPSHOT-2016-03-24-a
  - ~/.swiftenv/bin/swiftenv global DEVELOPMENT-SNAPSHOT-2016-03-24-a
  - ~/.swiftenv/bin/swiftenv rehash
script:
  - swift build
  # - swift test
